name: Generate Snake Animation

on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate snake animation
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ZeshanDev1
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Deploy to output branch
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
          commit_message: "feat: generate snake animation"